# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/model/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
schema = 'chores_manager'
filter = { only_tables = []}

[migrations_directory]
dir = "/home/piotrek/GitHub/Chores-Manager/migrations"
